### ISSUE TITLE
Add a link to Tiger to the readme

### ISSUE THREAD

**Issue by bjorn3** [Y-Nak/tiger-cranelift#1]
I assume https://www.lrde.epita.fr/~tiger/tiger.html is the correct link?

**Comment by Y-Nak** [comment]
Thanks for opening an issue! Sorry for late response, I missed this issue.
Yes, https://www.lrde.epita.fr/~tiger/tiger.html is the correct link, some features are still missing though.
I'll add a link later.

**Comment by bjorn3** [comment]
Thanks!

**Comment by Y-Nak** [comment]
Thank you too!
